let currentTask="",running=false,cancelled=false,step=0,plan=null,last="(none yet)",tabId=null;
const maxSteps=30,$=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));let recentActions=[];
function state(s){const e=$("#state");if(e)e.textContent=s}
function log(s,c=""){const host=$("#log");if(!host)return;const e=document.createElement("div");e.className="event "+c;e.textContent=s;host.appendChild(e);e.scrollIntoView({block:"nearest"})}
async function activeTab(){if(tabId){try{return await chrome.tabs.get(tabId)}catch(_){tabId=null}}const ts=await chrome.tabs.query({});return ts.find(t=>t.active&&/^https?:/.test(t.url||""))||ts.find(t=>/^https?:/.test(t.url||""))}
async function sendRaw(type,payload={}){const id=tabId||(await activeTab())?.id;if(!id)throw new Error("No web tab");tabId=id;return chrome.tabs.sendMessage(id,{type,...payload})}
async function ensureActuator(timeout=10000){const end=Date.now()+timeout;let lastErr;while(Date.now()<end){try{const r=await sendRaw("OBSERVE");if(r?.ok)return r;lastErr=new Error(r?.message||"Actuator not ready")}catch(e){lastErr=e;try{await chrome.scripting.executeScript({target:{tabId},files:["content.js"]})}catch(_){ } }await sleep(350)}throw new Error("Не удалось подключиться к веб-вкладке после навигации: "+(lastErr?.message||"timeout"))}
async function msg(type,payload={}){if(type==="OBSERVE")return ensureActuator();await ensureActuator();return sendRaw(type,payload)}
async function backend(type,payload){return new Promise((resolve,reject)=>chrome.runtime.sendMessage({type,payload},r=>{if(chrome.runtime.lastError)return reject(new Error(chrome.runtime.lastError.message));if(!r?.ok)return reject(new Error(r?.error||"Bridge unavailable"));resolve(r.data)}))}
async function human(q,{confirmOnly=false}={}){return new Promise(resolve=>{const h=$("#human");if(!h)return resolve("");h.replaceChildren();const card=document.createElement("div");card.className="ask";const text=document.createElement("div");text.textContent=q;card.appendChild(text);let input=null;if(!confirmOnly){input=document.createElement("input");input.placeholder="Ответ (не вводите пароли или коды)";card.appendChild(input)}const buttons=document.createElement("div");buttons.className="buttons";const yes=document.createElement("button");yes.textContent=confirmOnly?"Разрешить":"Продолжить";const no=document.createElement("button");no.textContent=confirmOnly?"Запретить":"Отмена";buttons.append(yes,no);card.appendChild(buttons);h.appendChild(card);yes.addEventListener("click",()=>{const v=input?.value?.trim()||"yes";h.replaceChildren();resolve(v)});no.addEventListener("click",()=>{h.replaceChildren();resolve("")});input?.focus()})}
async function run(){if(running)return;currentTask=$("#task")?.value.trim()||"";if(!currentTask)return;if(!tabId){const t=await activeTab();tabId=t?.id}if(!tabId){state("Откройте обычную веб-страницу");return}running=true;cancelled=false;step=0;last="(none yet)";recentActions=[];$("#log").replaceChildren();state("Planning…");
try{let obs=await msg("OBSERVE");plan=await backend("AGENT_PLAN",{task:currentTask,observation:obs.observation});$("#plan").textContent=(plan.steps||[]).map((x,i)=>`${i+1}. ${x}`).join("\n")||"—";state("Working…");
while(running&&!cancelled&&step++<maxSteps){obs=await msg("OBSERVE");log(`Шаг ${step}: анализ`);const d=await backend("AGENT_DECIDE",{task:currentTask,observation:obs.observation,last_action:last,plan});if(d.verification&&!d.verification.complete)log("Verifier: "+(d.verification.missing||[]).join("; "),"warn");if(d.kind==="finish"){log(d.text||"Готово","ok");state("Done · verified");running=false;return}if(d.name==="ask_user"){const q=d.arguments?.question||"Нужны данные пользователя";if(/password|парол|verification code|код подтверждения|2fa|otp/i.test(q)){log("🔒 Агент не запрашивает пароли или коды. Выполните вход вручную в браузере и нажмите «Продолжить».","warn");last="USER: "+await human("Выполните вход вручную в управляемой вкладке. Пароль и коды агенту не передавайте.",{confirmOnly:true})}else last="USER: "+await human(q);continue}const sig=d.name+" "+JSON.stringify(d.arguments||{});
if(recentActions.slice(-2).every(x=>x===sig)&&recentActions.length>=2){last="RECOVERY: identical action repeated twice; inspect the current page and choose a different tool or element.";log("↻ Recovery: остановлен цикл повторяющихся действий","warn");recentActions=[];await sleep(350);continue}
recentActions.push(sig);recentActions=recentActions.slice(-4);
log("→ "+sig,"tool");let r=await msg("ACT",{name:d.name,args:d.arguments||{}});if(r?.blocked){const answer=await human(r.message+" Разрешить это действие?",{confirmOnly:true});if(!answer){last="SAFETY: user denied "+d.name;log("Действие отменено пользователем","warn");continue}r=await msg("ACT",{name:d.name,args:{...(d.arguments||{}),confirmed:true}})}last=d.name+" -> "+(r?.message||"no result");log((r?.ok?"✓ ":"↻ ")+last,r?.ok?"ok":"warn");if(d.name==="navigate"||d.name==="back")await ensureActuator(12000);else await sleep(250)}
if(running)state("Step limit");running=false}catch(e){log("Ошибка: "+e.message,"err");state("Error");running=false}}
$("#run")?.addEventListener("click",run);$("#stop")?.addEventListener("click",()=>{cancelled=true;running=false;state("Stopped")});$("#close")?.addEventListener("click",()=>window.close());
chrome.storage.local.get(["pendingTask","targetTabId"],v=>{if(v.targetTabId)tabId=v.targetTabId;if(v.pendingTask){const t=$("#task");if(t)t.value=v.pendingTask;chrome.storage.local.remove(["pendingTask"]);run()}});
