let currentTask="",running=false,cancelled=false,step=0,plan=null,last="(none yet)",tabId=null;const maxSteps=30,$=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function state(s){$("#state").textContent=s}function log(s,c=""){const e=document.createElement("div");e.className="event "+c;e.textContent=s;$("#log").appendChild(e);e.scrollIntoView()}
async function activeTab(){if(tabId){try{return await chrome.tabs.get(tabId)}catch(_){}}const ts=await chrome.tabs.query({active:true});return ts.find(t=>/^https?:/.test(t.url||""))}
async function msg(type,payload={}){const id=tabId||(await activeTab())?.id;if(!id)throw new Error("No web tab");try{return await chrome.tabs.sendMessage(id,{type,...payload})}catch(e){try{await chrome.scripting.executeScript({target:{tabId:id},files:["content.js"]});return await chrome.tabs.sendMessage(id,{type,...payload})}catch(x){throw new Error("Не удалось подключиться к исходной веб-вкладке: "+x.message)}}}
async function backend(type,payload){return new Promise((resolve,reject)=>chrome.runtime.sendMessage({type,payload},r=>{if(chrome.runtime.lastError)return reject(new Error(chrome.runtime.lastError.message));if(!r?.ok)return reject(new Error(r?.error||"Bridge unavailable"));resolve(r.data)}))}
async function human(q){return new Promise(resolve=>{const h=$("#human");h.innerHTML='<div class="ask"><div></div><input placeholder="Ответ"><div class="buttons"><button id="yes">Продолжить</button><button id="no">Отмена</button></div></div>';h.querySelector("div div").textContent=q;h.querySelector("#yes").onclick=()=>{const v=h.querySelector("input").value;h.innerHTML="";resolve(v||"yes")};h.querySelector("#no").onclick=()=>{h.innerHTML="";resolve("")}})}
async function run(){if(running)return;currentTask=$("#task").value.trim();if(!currentTask)return;const t=await activeTab();if(!tabId)tabId=t?.id;if(!tabId){state("Откройте обычную веб-страницу");return}running=true;cancelled=false;step=0;last="(none yet)";$("#log").innerHTML="";state("Planning…");
try{let obs=await msg("OBSERVE");plan=await backend("AGENT_PLAN",{task:currentTask,observation:obs.observation});$("#plan").textContent=(plan.steps||[]).map((x,i)=>`${i+1}. ${x}`).join("\n")||"—";state("Working…");
while(running&&!cancelled&&step++<maxSteps){obs=await msg("OBSERVE");log(`Шаг ${step}: анализ`);const d=await backend("AGENT_DECIDE",{task:currentTask,observation:obs.observation,last_action:last,plan});if(d.verification&&!d.verification.complete)log("Verifier: "+(d.verification.missing||[]).join("; "),"warn");if(d.kind==="finish"){log(d.text||"Готово","ok");state("Done · verified");running=false;return}if(d.name==="ask_user"){last="USER: "+await human(d.arguments?.question||"Нужны данные пользователя");continue}log("→ "+d.name+" "+JSON.stringify(d.arguments||{}),"tool");let r=await msg("ACT",{name:d.name,args:d.arguments||{}});
        if(r.blocked){
          const answer=await human(r.message+" Разрешить это действие?");
          if(!answer){last="SAFETY: user denied "+d.name;log("Действие отменено пользователем","warn");continue}
          r=await msg("ACT",{name:d.name,args:{...(d.arguments||{}),confirmed:true}});
        }
        last=d.name+" -> "+r.message;log((r.ok?"✓ ":"↻ ")+last,r.ok?"ok":"warn");if(d.name==="navigate"||d.name==="back"){await sleep(1200)}else await sleep(300)}if(running)state("Step limit");running=false}catch(e){log("Ошибка: "+e.message,"err");state("Error");running=false}}
$("#run").onclick=run;$("#stop").onclick=()=>{cancelled=true;running=false;state("Stopped")};$("#close").onclick=()=>window.close();
chrome.storage.local.get(["pendingTask","targetTabId"],v=>{if(v.targetTabId)tabId=v.targetTabId;if(v.pendingTask){$("#task").value=v.pendingTask;chrome.storage.local.remove(["pendingTask"]);run();}});
