(()=>{if(window.__browserAgentActuator)return;window.__browserAgentActuator=true;
const REF="data-browser-agent-ref",sleep=ms=>new Promise(r=>setTimeout(r,ms));
const BASE='a,button,input,textarea,select,[role="button"],[role="link"],[role="menuitem"],[role="option"],[role="tab"],[role="checkbox"],[role="radio"],[role="textbox"],[role="searchbox"],[contenteditable="true"],[tabindex]';
function visible(e){if(!(e instanceof Element))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity||1)!==0&&r.width>1&&r.height>1}
function roots(){const out=[document],q=[document.documentElement];while(q.length){const n=q.shift();if(!n)continue;if(n.shadowRoot){out.push(n.shadowRoot);q.push(...n.shadowRoot.querySelectorAll("*"))}q.push(...n.children)}return out}
function allCandidates(){const set=new Set();for(const root of roots())for(const e of root.querySelectorAll(BASE))if(visible(e))set.add(e);return [...set]}
function label(e){const id=e.id,lab=id?document.querySelector(`label[for="${CSS.escape(id)}"]`):null;return[e.getAttribute("aria-label"),e.getAttribute("aria-labelledby")&&document.getElementById(e.getAttribute("aria-labelledby"))?.innerText,e.getAttribute("placeholder"),e.getAttribute("title"),e.getAttribute("name"),lab?.innerText,e.innerText,e.value].filter(Boolean).join(" ").replace(/\s+/g," ").trim()}
function observe(){document.querySelectorAll("["+REF+"]").forEach(e=>e.removeAttribute(REF));const candidates=allCandidates();const es=candidates.sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),av=ar.bottom>=0&&ar.top<=innerHeight?0:1,bv=br.bottom>=0&&br.top<=innerHeight?0:1;return av-bv||Math.abs(ar.top-innerHeight/2)-Math.abs(br.top-innerHeight/2)}).slice(0,70);
const elements=es.map((e,i)=>{const ref="e"+(i+1);e.setAttribute(REF,ref);const r=e.getBoundingClientRect();return{ref,tag:e.tagName.toLowerCase(),role:e.getAttribute("role")||"",type:e.getAttribute("type")||"",text:(e.innerText||e.value||"").replace(/\s+/g," ").trim().slice(0,180),name:label(e).slice(0,220),placeholder:e.getAttribute("placeholder")||"",href:e.tagName==="A"?(e.href||"").slice(0,220):"",editable:e.isContentEditable||["INPUT","TEXTAREA"].includes(e.tagName),viewport:r.bottom>=0&&r.top<=innerHeight}});
return["URL: "+location.href,"TITLE: "+document.title,"","INTERACTIVE ELEMENTS:",...elements.map(e=>`[${e.ref}] ${Object.entries(e).filter(([k,v])=>k!=="ref"&&v!==""&&v!==false).map(([k,v])=>k+"="+JSON.stringify(v)).join(" | ")}`),"","VISIBLE TEXT:",(document.body?.innerText||"").replace(/\s+/g," ").trim().slice(0,2800)].join("\n")}
function findRef(root,ref){if(root.querySelector){const e=root.querySelector(`[${REF}="${CSS.escape(ref)}"]`);if(e)return e;for(const n of root.querySelectorAll("*"))if(n.shadowRoot){const x=findRef(n.shadowRoot,ref);if(x)return x}}return null}
function el(ref){const e=findRef(document,ref);if(!e)throw Error("Stale/missing ref "+ref);return e}
function risky(e){const t=[e.innerText,e.value,e.getAttribute("aria-label"),e.href].filter(Boolean).join(" ").toLowerCase();return["delete","remove","pay","purchase","buy now","place order","send money","удалить","оплатить","купить","оформить заказ","перевести"].some(x=>t.includes(x))}
function nativeSet(e,text){if("value"in e){const proto=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:e instanceof HTMLInputElement?HTMLInputElement.prototype:null,setter=proto&&Object.getOwnPropertyDescriptor(proto,"value")?.set;if(setter)setter.call(e,text);else e.value=text}else if(e.isContentEditable)e.textContent=text;else throw Error("Element is not editable")}
async function act(n,a){if(n==="navigate"){if(a.url===location.href)return"Already at "+a.url;location.assign(a.url);return"Navigating"}if(n==="back"){history.back();return"Went back"}if(n==="scroll"){scrollBy({top:a.amount||700,behavior:"smooth"});await sleep(450);return"Scrolled"}if(n==="wait"){await sleep(Math.min(Math.max(a.milliseconds||1000,100),5000));return"Waited"}const e=el(a.ref);
if(n==="click"){if(risky(e)&&!a.confirmed)return{blocked:true,message:"Confirmation required: "+(e.innerText||e.value||a.ref)};e.scrollIntoView({block:"center"});e.focus({preventScroll:true});e.click();await sleep(500);return"Clicked "+a.ref}
if(n==="type"){e.scrollIntoView({block:"center"});e.focus({preventScroll:true});if(a.clear!==false){if(e.isContentEditable){e.textContent=""}else nativeSet(e,"")}nativeSet(e,a.text);try{e.dispatchEvent(new InputEvent("input",{bubbles:true,inputType:"insertText",data:a.text}))}catch(_){e.dispatchEvent(new Event("input",{bubbles:true}))}e.dispatchEvent(new Event("change",{bubbles:true}));if(a.submit){for(const type of ["keydown","keypress","keyup"])e.dispatchEvent(new KeyboardEvent(type,{key:"Enter",code:"Enter",keyCode:13,which:13,bubbles:true,cancelable:true}));if(e.form&&typeof e.form.requestSubmit==="function")e.form.requestSubmit()}await sleep(500);return"Typed "+a.ref}
if(n==="press"){e.focus({preventScroll:true});for(const type of ["keydown","keypress","keyup"])e.dispatchEvent(new KeyboardEvent(type,{key:a.key,code:a.key,bubbles:true,cancelable:true}));return"Pressed "+a.key}throw Error("Unknown tool "+n)}
chrome.runtime.onMessage.addListener((m,_s,reply)=>{if(m.type==="OBSERVE"){try{reply({ok:true,observation:observe()})}catch(e){reply({ok:false,message:e.message})}return}if(m.type==="ACT"){act(m.name,m.args||{}).then(x=>reply(typeof x==="object"?{ok:false,...x}:{ok:true,message:x})).catch(e=>reply({ok:false,message:e.message}));return true}})})();